version: '3.9'
name: atito-hack-ai

services:
  streamlit:
    image: python:3.9-slim
    container_name: atito_frontend
    ports:
      - '8501:8501'
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && streamlit run ATITO-H4CK-AI.py"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: python:3.9-slim
    container_name: atito_backend
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python BACKEND.py serve --host 0.0.0.0 --port 8000"
    restart: unless-stopped